### PR TITLE
Homework Session 1

### PR DESCRIPTION
**Pull request by StefanescuEduard**

### CODE REVIEW

**Comment by CosminBarbus** [comment]
Please create a folder HelloWorld and place the solution there.
Thank you

**Comment by StefanescuEduard** [comment]
I need to create a folder in master branch or in the branch that I created?

**Comment by CosminBarbus** [comment]
Create the folder in the Homework Session 1 branch

**Comment by StefanescuEduard** [comment]
I created the folder HelloWorld, and I added the solution there.

**Comment by CosminBarbus** [comment]
Now you have files duplicated
It should be like this:
 - HelloWorld (today's homework)
      - HelloWorld.sln
      - HelloWorld

**Comment by StefanescuEduard** [comment]
It is ok, if I a create a new branch with name HomeworkSession1 and I will upload the folder HelloWorld there? Because I can't delete the folder Session1 and if I rename it, will not work, if someone try to run the solution.

**Comment by CosminBarbus** [comment]
Yes, you can create another one

**Pull request merged**
